name: 'Validate'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    name: 'Code linting'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v4'

      - name: 'Set up Python'
        uses: 'actions/setup-python@v5'
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: 'Install requirements'
        run: 'python3 -m pip install -r requirements.txt'

      - name: 'Run linter check'
        run: 'python3 -m ruff check .'

      - name: 'Run linter format'
        run: 'python3 -m ruff format . --check'

  hassfest:
    name: 'Hassfest validation'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v4'

      - name: 'Run hassfest validation'
        uses: 'home-assistant/actions/hassfest@master'

  hacs:
    name: 'HACS validation'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v4'

      - name: 'Run HACS validation'
        uses: 'hacs/action@main'
        with:
          category: 'integration'
